import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import HeaderComponet from "@/Components/headerComponent/Page";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-300 overflow-x-hidden w-full min-h-screen flex flex-col items-center">
        <header>
          <HeaderComponet />
        </header>
        <main className="w-full max-w-screen-lg px-2 flex-1">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
